/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class FSMElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.FSM");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFSMAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFSMKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cStateAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cStateInitStateParserRuleCall_4_0 = (RuleCall)cStateAssignment_4.eContents().get(0);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStateAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cStateFinalStateParserRuleCall_6_0 = (RuleCall)cStateAssignment_6.eContents().get(0);
		private final Keyword cCommaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Assignment cStateAssignment_8_0 = (Assignment)cGroup_8.eContents().get(0);
		private final RuleCall cStateStateParserRuleCall_8_0_0 = (RuleCall)cStateAssignment_8_0.eContents().get(0);
		private final Group cGroup_8_1 = (Group)cGroup_8.eContents().get(1);
		private final Keyword cCommaKeyword_8_1_0 = (Keyword)cGroup_8_1.eContents().get(0);
		private final Alternatives cAlternatives_8_1_1 = (Alternatives)cGroup_8_1.eContents().get(1);
		private final Assignment cStateAssignment_8_1_1_0 = (Assignment)cAlternatives_8_1_1.eContents().get(0);
		private final RuleCall cStateStateParserRuleCall_8_1_1_0_0 = (RuleCall)cStateAssignment_8_1_1_0.eContents().get(0);
		private final Assignment cTransitionAssignment_8_1_1_1 = (Assignment)cAlternatives_8_1_1.eContents().get(1);
		private final RuleCall cTransitionTransitionParserRuleCall_8_1_1_1_0 = (RuleCall)cTransitionAssignment_8_1_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//FSM:
		//	{FSM}
		//	'FSM'
		//	name=EString
		//	'{'
		//	state+=InitState ","
		//	state+=FinalState "," (state+=State ("," (state+=State | transition+=Transition))*)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{FSM} 'FSM' name=EString '{' state+=InitState "," state+=FinalState "," (state+=State ("," (state+=State |
		//transition+=Transition))*)? '}'
		public Group getGroup() { return cGroup; }
		
		//{FSM}
		public Action getFSMAction_0() { return cFSMAction_0; }
		
		//'FSM'
		public Keyword getFSMKeyword_1() { return cFSMKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//state+=InitState
		public Assignment getStateAssignment_4() { return cStateAssignment_4; }
		
		//InitState
		public RuleCall getStateInitStateParserRuleCall_4_0() { return cStateInitStateParserRuleCall_4_0; }
		
		//","
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
		
		//state+=FinalState
		public Assignment getStateAssignment_6() { return cStateAssignment_6; }
		
		//FinalState
		public RuleCall getStateFinalStateParserRuleCall_6_0() { return cStateFinalStateParserRuleCall_6_0; }
		
		//","
		public Keyword getCommaKeyword_7() { return cCommaKeyword_7; }
		
		//(state+=State ("," (state+=State | transition+=Transition))*)?
		public Group getGroup_8() { return cGroup_8; }
		
		//state+=State
		public Assignment getStateAssignment_8_0() { return cStateAssignment_8_0; }
		
		//State
		public RuleCall getStateStateParserRuleCall_8_0_0() { return cStateStateParserRuleCall_8_0_0; }
		
		//("," (state+=State | transition+=Transition))*
		public Group getGroup_8_1() { return cGroup_8_1; }
		
		//","
		public Keyword getCommaKeyword_8_1_0() { return cCommaKeyword_8_1_0; }
		
		//state+=State | transition+=Transition
		public Alternatives getAlternatives_8_1_1() { return cAlternatives_8_1_1; }
		
		//state+=State
		public Assignment getStateAssignment_8_1_1_0() { return cStateAssignment_8_1_1_0; }
		
		//State
		public RuleCall getStateStateParserRuleCall_8_1_1_0_0() { return cStateStateParserRuleCall_8_1_1_0_0; }
		
		//transition+=Transition
		public Assignment getTransitionAssignment_8_1_1_1() { return cTransitionAssignment_8_1_1_1; }
		
		//Transition
		public RuleCall getTransitionTransitionParserRuleCall_8_1_1_1_0() { return cTransitionTransitionParserRuleCall_8_1_1_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class StateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.State");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStateAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStateKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//State:
		//	{State}
		//	'state'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{State} 'state' name=EString
		public Group getGroup() { return cGroup; }
		
		//{State}
		public Action getStateAction_0() { return cStateAction_0; }
		
		//'state'
		public Keyword getStateKeyword_1() { return cStateKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class InitStateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.InitState");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cInitStateAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStateinitKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//InitState:
		//	{InitState}
		//	'stateinit'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{InitState} 'stateinit' name=EString
		public Group getGroup() { return cGroup; }
		
		//{InitState}
		public Action getInitStateAction_0() { return cInitStateAction_0; }
		
		//'stateinit'
		public Keyword getStateinitKeyword_1() { return cStateinitKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class FinalStateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.FinalState");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFinalStateAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStatefinalKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//FinalState:
		//	{FinalState}
		//	'statefinal'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{FinalState} 'statefinal' name=EString
		public Group getGroup() { return cGroup; }
		
		//{FinalState}
		public Action getFinalStateAction_0() { return cFinalStateAction_0; }
		
		//'statefinal'
		public Keyword getStatefinalKeyword_1() { return cStatefinalKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Transition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTransitionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTrKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Assignment cStateStartAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cStateStartStateCrossReference_3_0 = (CrossReference)cStateStartAssignment_3.eContents().get(0);
		private final RuleCall cStateStartStateIDTerminalRuleCall_3_0_1 = (RuleCall)cStateStartStateCrossReference_3_0.eContents().get(1);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cStateEndAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cStateEndStateCrossReference_5_0 = (CrossReference)cStateEndAssignment_5.eContents().get(0);
		private final RuleCall cStateEndStateIDTerminalRuleCall_5_0_1 = (RuleCall)cStateEndStateCrossReference_5_0.eContents().get(1);
		
		//Transition:
		//	{Transition}
		//	'tr' name=EString stateStart=[State] '->' stateEnd=[State];
		@Override public ParserRule getRule() { return rule; }
		
		//{Transition} 'tr' name=EString stateStart=[State] '->' stateEnd=[State]
		public Group getGroup() { return cGroup; }
		
		//{Transition}
		public Action getTransitionAction_0() { return cTransitionAction_0; }
		
		//'tr'
		public Keyword getTrKeyword_1() { return cTrKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//stateStart=[State]
		public Assignment getStateStartAssignment_3() { return cStateStartAssignment_3; }
		
		//[State]
		public CrossReference getStateStartStateCrossReference_3_0() { return cStateStartStateCrossReference_3_0; }
		
		//ID
		public RuleCall getStateStartStateIDTerminalRuleCall_3_0_1() { return cStateStartStateIDTerminalRuleCall_3_0_1; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_4() { return cHyphenMinusGreaterThanSignKeyword_4; }
		
		//stateEnd=[State]
		public Assignment getStateEndAssignment_5() { return cStateEndAssignment_5; }
		
		//[State]
		public CrossReference getStateEndStateCrossReference_5_0() { return cStateEndStateCrossReference_5_0; }
		
		//ID
		public RuleCall getStateEndStateIDTerminalRuleCall_5_0_1() { return cStateEndStateIDTerminalRuleCall_5_0_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	
	
	private final FSMElements pFSM;
	private final StateElements pState;
	private final InitStateElements pInitState;
	private final FinalStateElements pFinalState;
	private final TransitionElements pTransition;
	private final EStringElements pEString;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pFSM = new FSMElements();
		this.pState = new StateElements();
		this.pInitState = new InitStateElements();
		this.pFinalState = new FinalStateElements();
		this.pTransition = new TransitionElements();
		this.pEString = new EStringElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//FSM:
	//	{FSM}
	//	'FSM'
	//	name=EString
	//	'{'
	//	state+=InitState ","
	//	state+=FinalState "," (state+=State ("," (state+=State | transition+=Transition))*)?
	//	'}';
	public FSMElements getFSMAccess() {
		return pFSM;
	}
	
	public ParserRule getFSMRule() {
		return getFSMAccess().getRule();
	}
	
	//State:
	//	{State}
	//	'state'
	//	name=EString;
	public StateElements getStateAccess() {
		return pState;
	}
	
	public ParserRule getStateRule() {
		return getStateAccess().getRule();
	}
	
	//InitState:
	//	{InitState}
	//	'stateinit'
	//	name=EString;
	public InitStateElements getInitStateAccess() {
		return pInitState;
	}
	
	public ParserRule getInitStateRule() {
		return getInitStateAccess().getRule();
	}
	
	//FinalState:
	//	{FinalState}
	//	'statefinal'
	//	name=EString;
	public FinalStateElements getFinalStateAccess() {
		return pFinalState;
	}
	
	public ParserRule getFinalStateRule() {
		return getFinalStateAccess().getRule();
	}
	
	//Transition:
	//	{Transition}
	//	'tr' name=EString stateStart=[State] '->' stateEnd=[State];
	public TransitionElements getTransitionAccess() {
		return pTransition;
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
